### ISSUE TITLE
setup fail

### ISSUE THREAD

**Issue by userzimmermann** [webuildcity/wbc#15]
Hi.
Unfortunately, **setup.py** is not working properly. The uploaded source package on https://pypi.python.org/pypi/webuildcity/0.1.1 is unusable. It contains no actual modules. The problem is the extra **lib/** dir for the `wbc` package source. You either have to add `package_dir={'': 'lib'}` to your `setup()` call and generate the `packages` list with `find_packages('lib')` or move `wbc` to the repository root dir. I would prefer the latter.

**Comment by vse** [comment]
I tried moving everything out of the lib dir and had to add a manifest file to get templates and static files included and everything seems to work. Also checked that `wbh` works as intended with the wbc python module. #16

**Comment by jochenklar** [comment]
maybe we should rename the whole directory to 'webuildcity' to match the name of the pypi package.

**Comment by userzimmermann** [comment]
@jochenklar Or change the distribution (pypi package) name to **wbc** :)
It's still available...

**Comment by lundelius** [comment]
wbc wbc wbc!! :-)

Am 17/08/15 um 12:25 schrieb Stefan Zimmermann:

> @jochenklar https://github.com/jochenklar Or change the distribution 
> (pypi package) name to /wbc/ :)
> It's still available...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/webuildcity/wbc/issues/15#issuecomment-131769016.

## 

// Timo Lundelius
// timo@lundelius.com
// +49157 82901744
// Eidelstedter Weg 9, 20255 Hamburg, DE
// skype: timo.lundelius
// twitter: @timo_lundelius
// xing.com/profile/Timo_Lundelius
// linkedin.com/pub/timo-lundelius/27/92/8a7/

**Comment by vse** [comment]
I think django-webuildcity or django-wbc would be better.
